#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend Jujutsualfayo
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 517652-web-01 100.25.111.247:80 check
    server 517652-web-02 18.235.255.113:80 check " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart


